export const FETCH_CHATS_START = "FETCH_CHATS_START"
export const FETCH_CHATS_SUCCESS = "FETCH_CHATS_SUCCESS"
export const FETCH_CHATS_FAIL = "FETCH_CHATS_FAIL"
export const FETCH_CHATS_UPDATE = "FETCH_CHATS_UPDATE"

export const FETCH_MESSAGES_START = "FETCH_MESSAGES_START"
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS"
export const FETCH_MESSAGES_FAIL = "FETCH_MESSAGES_FAIL"
export const FETCH_MESSAGES_UPDATE = "FETCH_MESSAGES_UPDATE"
